services:
  auth-api:
    image: auth-api:latest
    container_name: auth-api
    build:
      context: .
      dockerfile: .Dockerfile
    depends_on:
      - auth-db
    environment:
      DATABASE_URL: 'postgresql://docker:docker@localhost:5432/users?schema=public'
      API_PORT: '3333'
      JWT_PRIVATE_KEY: 'LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktnd2dnU2tBZ0VBQW9JQkFRRHRyZERrZjA1alFUNUMKZUxlWWZXVC9zWDR3N0ZpL0NrZVNjTnNjV0tMOTM1R0RZY0NxV2xJSVZNRHdGSzFHcjVLc2VsVVdiTWxOUStNUAord2hzODJnTktxT0ZoN25SRVM4SWV5a3VseEVnVU9rMlVYcXROU1hja1E3R24xY0JydkNwSHE1TXFmVWxDeGlUCjcwSjZ3WXZPMVBlR1FHbUtBd0ViMzBqcHE2MXVma0JhN054eWpXVDlpV0ltcHZtS25BTkJveXBnVDVMaGw2TGwKQzM3QnhtdjYrYTJpOWlyR093dXppbWc3RmUveVg1Z0lpVWRyeEV1Y3VHeXA1eWJJNWJtZ04wWFp1Z21qalF6bgozQ0VYS1J0OEFmNlpJN0picmhzSEd6OVdHRU5sVllGaUpsbVhGZTUxcGhwRmNHOVJ6TUlwY2FYNU14eks1RURKCjVKSERRWmRGQWdNQkFBRUNnZ0VBRlY2MTgvMkFTa3RROGtBUlhkd1VheXNGeWhkT0NXcytzU3VGZitCMlV6WTUKU3FOTTQrUTRFUGl4MmtRNXFpdmFGN2p1RXBTWWF1S0tOV01nU0UrQVVRSys3aUFjZEhCRGx0TWdDa2paNk5wdApoWTFBNXZicTN4Q0owQkQralMreUFycTMrRHVseDMxZWFkcXUwd080OHRGU0toZDdoY1dzWVZtcm9Ccm4vcEdlCkRoMVEwMDhkSFVqUUVLMENpMzBvbnlMTnM4dW5aV0F0empPdmoyNHdhYnlOTjdnbWsrRTk5ODRnMVdhM1F2VjgKVjVCT1llRHAvY05WUUhYUGRXYXNuandqT1FpU0didTRrYjlQempDMms4Vmtvc25LcjhoUG1QV0EvSy85bHpNKwpOTzQrbS8wcERZZ3hrZTFHU1d4RnlYSWZWaGpORUxpZjBSZ3dXamZka1FLQmdRRCtMT0hvWHEvcjlFc1E0TmVCCkh1QUJrcnZFRnBDRWlBbnN1K3JITFMraDB5ZzZMYzBZMWVrWDMrQXVCcmNwNU13aXVNTjNlWTFvMkZWMzFST3IKeEMvZUZCK0xkMlNNN0RvK042ekF4bzVPK1BYdUd5SUYzRlNrdmc1Z0M2TC83aVF2dVNoQTRNZkVVNjdTeWVEawpzbmd3cmMwbnpySGlmR3pJdzFSRHAxSG56UUtCZ1FEdllwM3VRQ05tcER5aE1MeC9QZVFaLytrVVIvNDNnMEh2CmZkaVdRTVhOMUhMWjlGbi9mcmdaTUFEVVBOeVB6ZVdEVEh4MUtPQ0xYcVZXKzVPTi9xVGVxRklrUzdWQmg5NFUKUHNGVDNpWGEyWFhzSHU0ZjUvR0w4K1RBeUx0cVRCU21OK2c5N3pUbVExMU9OaDdiZ2kwVzN4MHJ3MUVhOWI1ZQptY3g2bEVVRldRS0JnUUR4REErU0Yzb3ZBeGJOZ3UzZGZqSmlTNDNXZ0srOWdHWXBKRzJiUnJjTmVQdUZjVG80CmUyVDdSMDJMV01NTDcvZklWZ0RKcFhUK0lXdXNvVjV1WHpnbUhGOXVIR1EzWVRBN0lRR3NNS0YxTTVYSG9lTzYKT3lIcXVuTlhrckdhbFhXcjdLVElJbVJSUkN0ZnJDU2p2cjFOTFFhSzRmTEJIODdxOXBOTE5icnZZUUtCZ1FDNwpQR3RDdXEvMXpHZ1B1OHJ6eXpqcWpSdUZYWG9kZVhETkhhV1dnRHMyN3dDV01XVmpUWDQ1VlM2UTBybkJVTTQvCmtFZVlhOHlWdGdXa3IwbU9PcXBCN1cyeUxmVXJ1RldmaUNZMnJ2NzAyam85NFVObmVVZVlxNzgwZXN6OEsxM0wKVk5jMStpOXFHeTZUeWdrQXNDVU1TcDdLYUE2OEE1Sk85QVRYcTdrQW9RS0JnRTB4c2V0bGxxS21GOGNSaDlOYgpPbGlYQVRwaGIrMlAwaDlGRTVxY3FFekIrS1g3ZDlWZGxTZ2VRaXlUR0tWUFBWZ0IvdXA5NGp4WEp2YUZHK2g2ClhwY2VKS0NpcHZycFJDM0xybWtLLzNFa3ZSanBZSHloTjRnakRTTDVVN1dxTWdtdXBsekFTRmhoamoyT3BGU04KVGJuMG1mK0lrZWtZcmR0RStyWlRxZ0UwCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K'
      JWT_PUBLIC_KEY: 'LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUE3YTNRNUg5T1kwRStRbmkzbUgxawovN0YrTU94WXZ3cEhrbkRiSEZpaS9kK1JnMkhBcWxwU0NGVEE4QlN0UnErU3JIcFZGbXpKVFVQakQvc0liUE5vCkRTcWpoWWU1MFJFdkNIc3BMcGNSSUZEcE5sRjZyVFVsM0pFT3hwOVhBYTd3cVI2dVRLbjFKUXNZays5Q2VzR0wKenRUM2hrQnBpZ01CRzk5STZhdXRibjVBV3V6Y2NvMWsvWWxpSnFiNWlwd0RRYU1xWUUrUzRaZWk1UXQrd2Nacgordm10b3ZZcXhqc0xzNHBvT3hYdjhsK1lDSWxIYThSTG5MaHNxZWNteU9XNW9EZEYyYm9KbzQwTTU5d2hGeWtiCmZBSCttU095VzY0YkJ4cy9WaGhEWlZXQllpWlpseFh1ZGFZYVJYQnZVY3pDS1hHbCtUTWN5dVJBeWVTUncwR1gKUlFJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg=='
    ports:
      - '3333:3333'
    networks:
      - auth-net
      - ms-net

  auth-db:
    image: bitnami/postgresql:latest
    container_name: auth-db
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: users
      PGDATA: /data/postgres
    volumes:
      - ./data:/data/postgres
    networks:
      - auth-net

networks:
  # Rede privada
  auth-net:
    name: auth-net
    driver: bridge

  # Rede pública
  ms-net:
    external: true
