version: '3.8'

services:
    #
    # frontend
    #
    frontend:
        build: ./frontend
        container_name: coffeechain-frontend
        ports:
            - "3000:80"
        environment:
            - GATEWAY_API_URL=http://gateway:5002
        restart: unless-stopped
        depends_on:
            - gateway
        networks:
            - public

    #
    # gateway
    #
    gateway:
        build: ./gateway
        container_name: coffeechain-gateway
        ports:
            - "5002:5002"
        environment:
            - AUTH_API_URL=http://auth-ms:3333
            - BLOCKCHAIN_API_URL=http://blockchain-ms:5001
            - SUMMARY_API_URL=http://summary-ai-ms:5000
            - API_GATEWAY_PORT=5002
            - API_GATEWAY_HOST=0.0.0.0
        depends_on:
            - auth-ms
            - blockchain-ms
            - summary-ai-ms
        restart: unless-stopped
        networks:
            - public
            - internal

    #
    # blockchain
    #
    blockchain-ms:
        build: ./blockchain
        container_name: coffeechain-blockchain-ms
        ports:
            - "5001:5001"
        environment:
            - FLASK_APP=run.py
            - FLASK_ENV=production
            - AUTH_API_URL=http://auth-ms:3333
        volumes:
            - blockchain_data:/app/data
        restart: unless-stopped
        networks:
            - internal

    #
    # auth ms
    #
    auth-ms:
        build: ./auth-ms  
        container_name: coffeechain-auth-ms
        environment:
            - DATABASE_URL=postgresql://postgres:postgres@auth-ms-postgres:5432/users?schema=public
        ports:
            - "3333:3333"  
        depends_on:
            - auth-ms-postgres  
        networks:
            - internal

    auth-ms-postgres:
        image: postgres:latest  
        container_name: coffeechain-auth-ms-postgres
        environment:
            - POSTGRES_DB=users
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - "5432:5432"  
        volumes:
            - postgres_data:/var/lib/postgresql
        networks:
            - internal

    #
    # summary-ai ms
    #
    summary-ai-ms:
        build: ./summary-ai
        container_name: coffeechain-summary-ai-ms
        ports:
            - "5000:5000"
        environment:
            - OLLAMA_URL=http://summary-ai-ms-ollama:11434
            - AUTH_API_URL=http://auth-ms:3333
            - OLLAMA_MODEL=llama3.2:1b
        depends_on:
            summary-ai-ms-ollama-init:
                condition: service_completed_successfully
        restart: unless-stopped
        networks:
            - internal

    summary-ai-ms-ollama:
        image: ollama/ollama:latest
        container_name: coffeechain-summary-ai-ms-ollama
        ports:
            - "11434:11434"
        environment:
            - OLLAMA_HOST=0.0.0.0:11434
            - OLLAMA_LOG_LEVEL=info
            - OLLAMA_CONTEXT_LENGTH=2048
        volumes:
            - ollama_data:/root/.ollama
        mem_limit: 4g
        restart: unless-stopped
        # ativate nvidia gpu
        # deploy:
        #     resources:
        #         reservations:
        #             devices:
        #               - driver: nvidia
        #                 count: all 
        #                 capabilities: [gpu]
        networks:
            - internal

    summary-ai-ms-ollama-init:
        image: curlimages/curl:latest
        container_name: coffeechain-summary-ai-ms-ollama-init
        env_file:
            - ./summary-ai/.env
        entrypoint: >
            sh -c "curl -X POST http://summary-ai-ms-ollama:11434/api/pull -d '{\"name\":\"llama3.2:1b\"}' && echo Model loaded"
        restart: on-failure
        networks:
            - internal

volumes:
    ollama_data:
    postgres_data:
    blockchain_data:

networks:
    public:
        external: false
    internal:
        external: false